nginx-php-web:
  image: richarvey/nginx-php-fpm:1.3.0
  container_name: nginx_php_web
  restart: always
  volumes:
   - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
   - ./conf/nginx/conf.d:/etc/nginx/sites-enabled
   - ./conf/nginx/ssl:/etc/nginx/ssl
   - /deploy/www:/var/www/html
   - /deploy/wwwlogs:/var/log/nginx
   - ./errors:/var/www/errors
  ports:
   - "80:80"
   - "443:443"
  privileged: true
  tty: true 
  restart: always    
